
import java.util.Objects;

/**
 * Represents a single financial investment project for the Job Sequencing
 * Problem. Implements Comparable to allow natural sorting by maximum expected
 * profit.
 */
public class InvestmentProject implements ISchedulableProject, Comparable<InvestmentProject> {

    // --- Attributes ---
    private String id;
    private String projectName;
    private String sector;
    private double profit;       // Investment Return in RM Billion
    private int jobsCreated;     // Number of jobs generated by the project
    private int deadline;        // Strict Deadline 
    private int assignedSlot;

    /**
     * Constructs a new InvestmentProject with built-in data validation.
     *
     * @param id Unique identifier for the project.
     * @param projectName Descriptive name of the project.
     * @param sector The economic sector (e.g., Tech, Real Estate).
     * @param profit Expected profit in RM Billions. Cannot be negative.
     * @param jobsCreated Estimated jobs created. Cannot be negative.
     * @param deadline The strict deadline slot. Must be greater than 0.
     * @throws IllegalArgumentException if invalid numeric data is provided.
     */
    public InvestmentProject(String id, String projectName, String sector,
            double profit, int jobsCreated, int deadline) {
        // Validation ensures bad data never enters the system (Rubric 1.6)
        if (profit < 0) {
            throw new IllegalArgumentException("Profit cannot be negative for project: " + id);
        }
        if (deadline <= 0) {
            throw new IllegalArgumentException("Deadline must be 1 or greater for project: " + id);
        }
        if (jobsCreated < 0) {
            throw new IllegalArgumentException("Jobs created cannot be negative for project: " + id);
        }

        this.id = id;
        this.projectName = projectName;
        this.sector = sector;
        this.profit = profit;
        this.jobsCreated = jobsCreated;
        this.deadline = deadline;
        this.assignedSlot = -1; // -1 indicates it is currently unscheduled
    }

    /**
     * Determines if this project can be legally scheduled in the given time
     * slot. Encapsulates the deadline logic within the domain object.
     */
    public boolean isSchedulableAt(int timeSlot) {
        // timeSlot is 1-indexed (Slot 1, Slot 2). 
        // Must be less than or equal to the deadline.
        return timeSlot <= this.deadline;
    }

    /**
     * Two projects are considered identical if they have the same unique ID.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InvestmentProject that = (InvestmentProject) o;
        return Objects.equals(id, that.id);
    }

    /**
     * Hashes the object based purely on its unique ID.
     */
    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    // --- Getters ---
    public String getId() {
        return id;
    }

    public String getProjectName() {
        return projectName;
    }

    public String getSector() {
        return sector;
    }

    public double getProfit() {
        return profit;
    }

    public int getJobsCreated() {
        return jobsCreated;
    }

    public int getDeadline() {
        return deadline;
    }

    // NEW: Getter for assigned slot
    public int getAssignedSlot() {
        return assignedSlot;
    }

    // --- Setters ---
    public void setId(String id) {
        this.id = id;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public void setSector(String sector) {
        this.sector = sector;
    }

    public void setProfit(double profit) {
        if (profit < 0) {
            throw new IllegalArgumentException("Profit cannot be negative.");
        }
        this.profit = profit;
    }

    public void setJobsCreated(int jobsCreated) {
        if (jobsCreated < 0) {
            throw new IllegalArgumentException("Jobs created cannot be negative.");
        }
        this.jobsCreated = jobsCreated;
    }

    public void setDeadline(int deadline) {
        if (deadline <= 0) {
            throw new IllegalArgumentException("Deadline must be 1 or greater.");
        }
        this.deadline = deadline;
    }

    // NEW: Setter for assigned slot
    public void setAssignedSlot(int assignedSlot) {
        this.assignedSlot = assignedSlot;
    }

    /**
     * Defines the default sorting behavior for the Collections framework. Sorts
     * descending: Highest Profit -> Lowest Profit.
     */
    @Override
    public int compareTo(InvestmentProject other) {
        // Double.compare safely handles decimal comparisons for RM Billions
        return Double.compare(other.profit, this.profit);
    }

    /**
     * Formats the project details into a clean, tabulated string for terminal
     * output. Dynamically adds the Scheduled Slot if the project has been
     * assigned one.
     */
    @Override
    public String toString() {
        // Removed the hardcoded words "Deadline:" and "Jobs:" and "Scheduled in Slot:" 
        // since the column headers and output loop handle that beautifully now.
        return String.format("%-5s | %-32s | %-15s | RM%6.1f bil | %12d | %,d",
                id, projectName, sector, profit, deadline, jobsCreated);
    }
}
